
import java.awt.Color;
import java.awt.Graphics;
import java.util.ArrayList;


public class MorseCodeFlasher extends javax.swing.JFrame {

    private int wDot = 100; //0.5 second interval
    private int wDash = 3*wDot;
    private int bLetter = 3*wDot;
    private int bWord = 7*wDot;
    private ArrayList <String> words;
    private ArrayList <String> code;
    
    
    public MorseCodeFlasher() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        panelFlasher = new javax.swing.JPanel();
        textField1 = new java.awt.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("FLASH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        panelFlasher.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout panelFlasherLayout = new javax.swing.GroupLayout(panelFlasher);
        panelFlasher.setLayout(panelFlasherLayout);
        panelFlasherLayout.setHorizontalGroup(
            panelFlasherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 821, Short.MAX_VALUE)
        );
        panelFlasherLayout.setVerticalGroup(
            panelFlasherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 486, Short.MAX_VALUE)
        );

        textField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelFlasher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(panelFlasher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String input = textField1.getText();
        words = new ArrayList <String>();
        
        //putting words into arrayList
        while(input.length()>0){
            int pos = input.indexOf(" ");

            if (pos != -1){
                 words.add(input.substring(0, pos));
                 input = input.substring(pos+1);
            }
            else{
                 words.add(input);
                 break;
            }
        }
        
        //printing words in arrayList
        System.out.println("Words to convert: ");
        for (String s: words){
            System.out.println(s);
        }

        // converting to morse
        code = WordToDash.convert(words);
        System.out.println("Words converted to morse: ");
        for (int k=0; k<words.size(); k++){
            System.out.println(words.get(k)+" ---> "+code.get(k));
        }
        
        //flashing
         Graphics g = panelFlasher.getGraphics();
         
         for (int k=0; k<code.size(); k++){
             for (int q=0; q<code.get(k).length(); q++){
                 String codeChar = code.get(k).substring(q,q+1);
                 if (codeChar.equals("*")){
                      g.setColor(Color.WHITE);
                      g.fillRect(0,0,panelFlasher.getWidth(), panelFlasher.getHeight() );
                       try {
                            Thread.sleep(wDot); 
                              g.setColor(Color.BLACK);
                            g.fillRect(0,0,panelFlasher.getWidth(), panelFlasher.getHeight() );
                            Thread.sleep(wDot);
                         }catch(Exception e) {
                            System.out.println("error in flash loop"); 
                         }
                 }
                 else if (codeChar.equals("-")){
                     g.setColor(Color.WHITE);
                      g.fillRect(0,0,panelFlasher.getWidth(), panelFlasher.getHeight() );
                        try {
                            Thread.sleep(wDash); 
                             g.setColor(Color.BLACK);
                            g.fillRect(0,0,panelFlasher.getWidth(), panelFlasher.getHeight() );
                            Thread.sleep(wDot);
                         }catch(Exception e) {
                            System.out.println("error in flash loop");             
                         }
                 }
                 else if (codeChar.equals("/")){
                        g.setColor(Color.BLACK);
                      g.fillRect(0,0,panelFlasher.getWidth(), panelFlasher.getHeight() );
                       try {
                            Thread.sleep(bLetter); 
                         }catch(Exception e) {
                            System.out.println("error in flash loop"); 
                         }     
                 }
                 else{ System.out.println("error during code to flashing process");}
                 
                  }
             try {
                      Thread.sleep(bWord-bLetter); 
                  }catch(Exception e) {
                      System.out.println("error during code to flashing process"); 
             }
         }
         
         System.out.println("DONE");
         
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField1ActionPerformed

 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MorseCodeFlasher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MorseCodeFlasher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MorseCodeFlasher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MorseCodeFlasher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MorseCodeFlasher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel panelFlasher;
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables
}
